name: Build and Save Docker Image

on:
  push:
    branches: [ "main", "develop", "split_by_http_methods" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        folder: [ get, post, put, delete ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t kezboards-${{ matrix.folder }}:${{ github.sha }} ./${{ matrix.folder }}

      - name: Save Docker image to tar file
        run: docker save -o kezboards-${{ matrix.folder }}.tar kezboards-${{ matrix.folder }}:${{ github.sha }}

      - name: Upload Docker image tar file
        uses: actions/upload-artifact@v3
        with:
          name: kezboards-${{ matrix.folder }}-tar
          path: kezboards-${{ matrix.folder }}.tar
